import {notFound} from 'next/navigation';
import './project.css';

const projects: Record<string,{name:string;subtitle:string;role:string;time:string;context:string;work:string[];outcome:string;note?:string}>={
  showability:{name:'SHOWAbility',subtitle:'A clearer path to participation.',role:'Research Assistant · Georgia Tech',time:'January 2025 – present',context:'A digital platform redesign grounded in the needs of community members, researchers, and organizational stakeholders.',work:['Synthesized stakeholder interviews, user research, and engagement data into recommendations for information architecture, content, and user flows.','Built a lightweight analytics dashboard connecting acquisition sources, content engagement, call-to-action conversion, and returning-user behavior.','Coordinated researchers, community stakeholders, designers, and leadership to turn differing priorities into requirements and next steps.'],outcome:'The work contributed to a 42% increase in qualified site engagement and a 27% improvement in repeat visitor retention.',note:'Reported project outcomes from my research role; these reflect a collaborative effort.'},
  seatscore:{name:'AI SeatScore',subtitle:'A better seat, on your terms.',role:'Independent project · Design & React development',time:'2026',context:'The best theater seat depends on the person choosing it. View quality, distance, accessibility, and personal preferences can pull in different directions.',work:['Designed a recommendation system that translates user preferences and seat attributes into ranked theater-seat suggestions.','Prototyped the complete decision flow in React, connecting preference inputs with recommendation logic.','Used structured user feedback to iterate on both the scoring model and the interface.'],outcome:'A personalized recommendation prototype that makes the tradeoffs behind a seat choice explicit.',note:'Prototype, rather than a launched commercial product. No production performance claims.'},
  opslens:{name:'OpsLens',subtitle:'Find the bottleneck. Test the next move.',role:'Self-directed · Python, SQL, Pandas & Streamlit',time:'2026',context:'A simulation of a multi-stage transaction workflow, built to understand how validation, review, escalation, and resolution affect one another.',work:['Created a workflow simulation with more than 50,000 synthetic events to study throughput, latency, rework, and queue buildup.','Used Python and SQL to identify bottlenecks, failure patterns, and stage dependencies.','Built an interactive dashboard for staffing, automation, and routing scenarios, then compared interventions by expected impact, effort, and downstream effects.'],outcome:'An interactive scenario-analysis dashboard and a decision memo summarizing the strongest opportunities for improvement.',note:'All events are synthetic. This is a systems-analysis project, not a claim about a live organization’s transactions.'},
  cnn:{name:'CNN Academy',subtitle:'Complex simulation. Clear participant experience.',role:'Program Strategy & Experience Design',time:'September 2024 – May 2026',context:'An interactive CNN Academy simulation serving more than 100 global participants across Abu Dhabi and Atlanta.',work:['Helped design and execute the simulation in collaboration with content, product, and facilitation teams.','Translated a multi-stage experience into clear participant workflows, instructions, and communications.','Synthesized feedback and engagement signals to identify recurring friction points.'],outcome:'A coordinated participant experience that made a complex sequence of activities easier to follow.',note:'My contribution focused on program strategy and experience design within a larger team.'}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const p=projects[(await params).slug];return{title:p?`${p.name} — Ashna Kasireddy`:'Project not found',description:p?.subtitle};}
export default async function Project({params}:{params:Promise<{slug:string}>}){const p=projects[(await params).slug];if(!p)notFound();return <main className="resume-project"><nav><a href="/#work">← Selected work</a><a href="/#about">Ashna Kasireddy</a><a href="mailto:akasireddy3@gatech.edu">Contact ↗</a></nav><header><p>{p.role}</p><h1>{p.name}</h1><h2>{p.subtitle}</h2><span>{p.time}</span></header><section><h2>Context</h2><p>{p.context}</p></section><section><h2>My contribution</h2><ol>{p.work.map((w,i)=><li key={w}><span>0{i+1}</span><p>{w}</p></li>)}</ol></section><section><h2>What came out of it</h2><div><p>{p.outcome}</p>{p.note&&<p className="project-note">{p.note}</p>}</div></section><footer><a href="/#work">Explore more work ↗</a><a href="/#about">About Ashna</a></footer></main>}
