export const metadata = { title: 'Pinwheels — Ashna Kasireddy', description: 'A Pinterest discovery concept that turns passive scrolling into purposeful exploration.' };
import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowDown,ArrowUpRight} from 'lucide-react';
import './pinwheels.css';
import './hero.css';

function Phone({screen}:{screen:'feed'|'spin'|'results'}){return <div className={`pw-phone ${screen}`}><div className="phone-top"><span>9:41</span><i/><b>•••</b></div><div className="phone-ui">
{screen==='feed'&&<><div className="pw-tabs"><span>For you</span><b>Pinwheels</b></div><div className="room-image"><div className="window"/><div className="sofa"/><div className="plant">✦</div><p>Japandi living room ✦<small>neutral, calm, and cozy</small></p></div><div className="feed-actions"><span>Save</span><span>Shop</span><b>Spin</b></div></>}
{screen==='spin'&&<><small className="screen-kicker">SPIN THIS IDEA</small><h3>Where should we<br/>take this idea?</h3><div className="spin-list">{['More colorful','Under $500','Small apartment','More vintage','Dark wood','Surprise me'].map((x,i)=><span key={x}><i>{['◒','$','⌂','◫','◧','✦'][i]}</i>{x}</span>)}</div></>}
{screen==='results'&&<><div className="pw-tabs"><span>Under $500</span><b>12 finds</b></div><h3>Budget-friendly ideas<br/><small>in a similar style</small></h3><div className="result-grid">{[1,2,3,4].map(x=><div key={x}><i className={`mini-room r${x}`}/><span>${[320,185,460,240][x-1]}</span></div>)}</div><button>Save this spin</button></>}
</div></div>}

export default function PinwheelsPage(){return <main className="pinwheels-page">
<nav className="pw-nav"><Link href="/#work"><ArrowLeft size={15}/> Selected work</Link><span>ASHNA KASIREDDY</span><a href="mailto:akasireddy3@gatech.edu">Contact ↗</a></nav>
<header className="pw-hero"><div className="pw-hero-copy"><span>CASE STUDY 01 · PINTEREST PRODUCT CONCEPT</span><h1>Pinwheels</h1><h2>Don’t just scroll.<br/>Follow the idea.</h2><p>A short-form discovery mode that turns passive scrolling into visual exploration, saving, and action.</p><div className="hero-meta"><span><b>ROLE</b>Product Designer</span><span><b>TIMELINE</b>Fall 2026</span><span><b>STATUS</b>Prototype tested</span></div><div className="hero-results"><span><b>+28%</b> idea saves</span><span><b>+34%</b> boards created</span><span><b>+21%</b> completion</span></div><a href="#snapshot">Read the case study <ArrowDown size={16}/></a></div><div className="pw-hero-art"><div className="hero-watermark" aria-hidden="true">FOLLOW<br/>THE IDEA</div><div className="hero-phones"><Phone screen="spin"/><Phone screen="feed"/><Phone screen="results"/></div></div></header>
<section className="pw-snapshot" id="snapshot"><div className="snapshot-title"><span>THE 10-SECOND VERSION</span><h2>I reframed short-form video around intent—not entertainment.</h2></div><div className="snapshot-grid"><article><small>THE TENSION</small><p>Pinterest users arrive asking what to make, wear, cook, or build. Existing short-form feeds are optimized to keep them watching.</p></article><article><small>MY MOVE</small><p>Designed a vertical discovery flow that lets people redirect an idea, explore objects, and save the outcome without breaking momentum.</p></article><article><small>MY ROLE</small><p>Product strategy, interaction model, end-to-end experience, visual design, prototyping, and concept validation.</p></article></div></section>
<section className="pw-impact"><header><span>PROTOTYPE TEST RESULTS</span><p>Directional results from concept testing—not shipped Pinterest metrics.</p></header><div><article><strong>+28%</strong><span>idea saves</span></article><article><strong>+34%</strong><span>boards created</span></article><article><strong>+21%</strong><span>session completion</span></article></div><blockquote>“Pinwheels makes Pinterest feel even more helpful and personal. It’s like having a creative partner.”<cite>— Prototype test participant</cite></blockquote></section>
<section className="pw-problem pw-section"><span className="section-no">01 / THE PRODUCT QUESTION</span><div><h2>What if short-form video helped answer the question—instead of distracting from it?</h2><p>Short-form video is exceptionally good at discovery, but most feeds optimize for entertainment and watch time. Pinterest has a different advantage: people arrive with intent. The opportunity was to preserve the momentum of a swipe while making every interaction lead somewhere useful.</p></div></section>
<section className="pw-phones"><header><span>02 / THE CORE EXPERIENCE</span><h2>One idea.<br/>Three purposeful moves.</h2></header><div className="phones-stage"><figure><Phone screen="feed"/><figcaption><b>01</b><span>Discover</span><p>Swipe through ideas tuned to what you want to do.</p></figcaption></figure><figure><Phone screen="spin"/><figcaption><b>02</b><span>Direct</span><p>Tell Pinterest where the idea should go next.</p></figcaption></figure><figure><Phone screen="results"/><figcaption><b>03</b><span>Act</span><p>Explore, compare, and save a concrete outcome.</p></figcaption></figure></div></section>
<section className="pw-decisions"><header><span>03 / PRODUCT DECISIONS</span><h2>The interface stays playful.<br/>The logic underneath is disciplined.</h2></header><div className="decision-grid"><article><b>01</b><h3>Make intent interactive</h3><p>“Spin” turns recommendation tuning into an explicit, lightweight choice rather than an invisible algorithmic guess.</p></article><article><b>02</b><h3>Preserve momentum</h3><p>Saving, shopping, visual search, and refinement remain inside the feed so inspiration does not dissolve into tab-switching.</p></article><article><b>03</b><h3>Design for action</h3><p>The loop ends in a board, product, or next idea—not another video. Completion is the product value.</p></article></div></section>
<section className="pw-flow"><div><span>04 / END-TO-END FLOW</span><h2>From a passing image<br/>to a plan worth keeping.</h2><ol>{['Enter the Pinwheels feed','Discover an inspiring idea','Save it in one tap','Choose “Spin this idea”','Refine the direction','Search within the image','Follow the inspiration trail','Build a board'].map((x,i)=><li key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</li>)}</ol></div><figure><Image src="/pinwheels/case-study-board.png" alt="Pinwheels concept case study showing its full product flow and prototype outcomes" width={1076} height={1620}/><figcaption>The complete concept board: tension, interaction model, experience flow, features, and validation.</figcaption></figure></section>
<section className="pw-reflection pw-section"><span className="section-no">05 / REFLECTION</span><div><h2>The strongest part wasn’t the feed. It was giving people control over what came next.</h2><p>The concept started as a content-format question and became an agency question: how can recommendation systems invite direction without turning discovery into a form? Next, I would validate whether “Spin” stays understandable across different Pinterest intents and separate novelty effects from durable saving behavior.</p><ul><li>Validate the language of “Spin” across user groups</li><li>Test recommendation trust and transparency</li><li>Measure durable behavior beyond novelty</li></ul></div></section>
<footer className="pw-footer"><span>NEXT CASE STUDY</span><Link href="/#work">ReCart <ArrowUpRight/></Link><small>Return to all selected work</small></footer>
</main>}
